### ISSUE TITLE
maptype argument does not have an effect

### ISSUE THREAD

**Issue by kondofersky** [fawda123/rStrava#95]
Hi there,

awesome package, thanks!

I noticed that the maptype argument in get_heat_map does not have an effect. I think it somehow does not get passed to the ggmap function because using ggmap by itself changes the maptype.

Here is what I used:
get_heat_map(act_data %>% slice(3), key = google_key, size = 2, distlab = F, col = 'Spectral', add_elev = T, f = 0.4, alpha = 1,  maptype = 'watercolor')
get_heat_map(act_data %>% slice(3), key = google_key, size = 2, distlab = F, col = 'Spectral', add_elev = T, f = 0.4, alpha = 1,  maptype = 'satellite')
get_heat_map(act_data %>% slice(3), key = google_key, size = 2, distlab = F, col = 'Spectral', add_elev = T, f = 0.4, alpha = 1,  maptype = 'roadmap')

They all produced the same plot.
![grafik](https://user-images.githubusercontent.com/32643049/215595946-5f55ef5d-a7d7-47ba-b2d0-33521ea11360.png)

As I said, those two give different (as expected) results:
ggmap(get_map(maptype = 'watercolor'))
ggmap(get_map(maptype = 'roadmap'))

To make the example fully reproducable, you would need an act_data object. I can send one if desired but probably you have enough.

Thanks for looking into it!

**Comment by fawda123** [comment]
@kondofersky sorry about that, the source argument was missing from the call to `get_map`.  Should be fixed now, just install the dev version and try again.

**Comment by kondofersky** [comment]
Hi @fawda123 and thanky ou for your reply! Sorry for asking again, but how do I install the dev version?

Tried with remotes::install_github('fawda123/rStrava') but no luck...

**Comment by fawda123** [comment]
@kondofersky the `install_github` function should work.  What errors are you seeing?

**Comment by kondofersky** [comment]
Hi @fawda123 

I am not seeing any errors but still having the same behaviour as in the original post. `maptype` argument does not change the map. 

Currently I have `rStrava` version 1.1.4.9000 installed. And in the description file I also see the time of package build:
2023-01-31. So I guess, I have the correct package.

Apparantely the argument still does not get passed I guess?

So, for example: 
`get_heat_map(last_act, key = google_key, size = 2, distlab = F, col = 'OrRd', add_elev = T, f = 0.1, alpha = 1,  maptype = 'satellite')`
is no different from 
`get_heat_map(last_act, key = google_key, size = 2, distlab = F, col = 'OrRd', add_elev = T, f = 0.1, alpha = 1,  maptype = 'watercolor')`

But plotting directly in `get_map()` does produce the different map styles, e.g.:
`ggmap(get_map(c(-97.14667, 31.5493), maptype = 'satellite'))`
`ggmap(get_map(c(-97.14667, 31.5493), maptype = 'watercolor'))`

This holds through for any maptype argument I tried.

Thanks for your help!

**Comment by fawda123** [comment]
Hi @kondofersky, are you using the `source` argument (satellite is `"google"`, default, others are `"stamen"`)?  These all work for me: 

```
get_heat_map(my_acts, acts = 1, key = google_key, maptype = 'satellite', f = 0.7)
```
![image](https://user-images.githubusercontent.com/3086881/217142571-b9a97bda-558f-4c6f-bae3-eb834de5cbda.png)

```
get_heat_map(my_acts, acts = 1, key = google_key, maptype = 'terrain', source = 'stamen', f = 0.5)
```
![image](https://user-images.githubusercontent.com/3086881/217142427-80631bf4-1f3d-463b-bf32-4387f1090859.png)

```
get_heat_map(my_acts, acts = 1, key = google_key, maptype = 'watercolor', source = 'stamen', f = 0.5)
```
![image](https://user-images.githubusercontent.com/3086881/217142388-7eb5e752-2bf2-4cb2-b221-a3b8f7b5d6ad.png)
